name: Bootstrap Vertical Tabs
markdown: redcarpet
highlighter: pygments

author: İsmail Demirbilek
description: Missing vertical-tabs component for Bootstrap 3
keywords: bootstrap 3, vertical, tabs, component
